
try:
    print("x")
except:
    print("something went wrong")
finally:
    print("The 'try except'id finished")
    